name: Node Tests Pipeline

permissions:
  contents: read
  checks: write

on:
  # Executa no push
  push:
    branches:
      - master

  # Execução manual pelo GitHub
  workflow_dispatch:

  # Execução agendada
  schedule:
    - cron: "0 22 * * *"


jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install dependencies
        run: npm ci


      - name: Run tests
        run: npm test


      - name: Publish Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Mocha Tests
          path: test-results.xml
          reporter: java-junit